services:
  mongodb:
    image: mongo:5.0
    container_name: nexus-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - nexus_data:/data/db
    restart: unless-stopped

  seeder:
    image: mongo:5.0
    container_name: nexus-seeder
    depends_on:
      - mongodb
    volumes:
      - ./NexusData_Output:/import/:ro,Z
    command: >
      bash -c "
      echo 'Waiting for MongoDB...';
      sleep 10;
      for file in /import/*.json; do 
        col=$$(basename \"$$file\" .json); 
        echo \"Importing $$col...\"; 
        mongoimport --host mongodb --username admin --password password --authenticationDatabase admin --db NexusLogisticsDB --collection \"$$col\" --file \"$$file\" --jsonArray; 
      done"

volumes:
  nexus_data:
    